import { MODULE_NAME } from './constants';

export const REMOVE_FAVORITES = `${MODULE_NAME}.REMOVE_FAVORITES`;
export const ADD_FAVORITES = `${MODULE_NAME}.ADD_FAVORITES`;
export const GET_MOVIES = `${MODULE_NAME}.GET_MOVIES`;
export const GET_MOVIES_SUCCESS = `${MODULE_NAME}.GET_MOVIES_SUCCESS`;
export const GET_MOVIES_FAILURE = `${MODULE_NAME}.GET_MOVIES_FAILURE`;
